Jarvis / OpenStack
Nicolas Lamirault
:revnumber: 0.1.0
:revdate: 03/09/2018
:description: Jarvis on OpenStack
:doctype: book
// Settings:
:compat-mode:
:experimental:
:icons: font
:listing-caption: Listing
:sectnums:
:toc:
:toclevels: 3
ifdef::backend-pdf[]
:title-logo-image: image:chapters/images/cover.svg[scaledwidth=30%,align=center]
:pygments-style: tango
//:source-highlighter: pygments
:source-highlighter: coderay
endif::[]

== Description

This project contains https://www.terraform.io/[Terraform] templates to help you deploy *Jarvis* on https://www.openstack.org/[OpenStack].

Prerequisites:

* An Openstack Cloud
* An Account, project and relevant access on your openstack cloud.

=== Openstack

Generate en `openstackrc` file

=== Terraform

Install https://www.terraform.io/[Terraform]

[source,bash]
----
terraform version
Terraform v0.11.3
----

== Installation

The available variables that can be configured are:
* **openstack_access_key**: Openstack username.
* **openstack_secret_key**: Openstack Password.
* **openstack_tenant_name**: The Tenant/Project name in Openstack.
* **openstack_key_name**: The name given to the SSH key which will be uploaded for use by the instances.
* **pub_key**: The actual contents of rsa_id.pub to upload as the public key.
* **pvt_key**: Path to the SSH private key file (Stays local. Used for provisioning.)
* **openstack_ssh_user**: SSH user (default ubuntu)
* **openstack_keystone_uri**: The Keystone API URL

Setup your informations :

----
$ export OPENSTACK_ACCESS_KEY="xxxx"
$ export OPENSTACK_SECRET_KEY="xxxx"
$ ...
----



=== Configure

Configure the terraform modules:

[source,bash]
----
terraform init
----

Copy and renamed *terraform.tfvars.sample* to *terraform.tfvars*.
Follow the instructions in the comments of the **terraform.tfvars.example** and
**variables.tf** file.

=== Evaluate

[source,bash]
----
terraform plan --var-file=terraform.tfvars
----

=== Deploy your cluster

[source,bash]
----
terraform apply --var-file=terraform.tfvars
----

=== Destroy the cluster

[source,bash]
----
terraform destroy --var-file=terraform.tfvars
----
